/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dionisio.view;

import dionisio.view.main.MenuPrincipal;
import dionisio.view.searchs.CepasPropriedadeSearch4;
import dionisio.view.searchs.ProdutividadeUvasSearch5;
import dionisio.view.searchs.PropriedadeProduçãoSearch3;
import dionisio.view.searchs.SafraVinhoSearch2;
import dionisio.view.searchs.VinhosViewSearch1;
import java.awt.Dimension;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.plaf.ColorUIResource;

/**
 *
 * @author Caio
 */
public class Workspace extends javax.swing.JInternalFrame {

    /**
     * Creates new form Workspace
     */
    public Workspace() {
        initComponents();
        jPanel2.setVisible(false);
        setImage();
    }

    public void setImage() {

        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/wine_1.png")));
    }

    public void setPosicao() throws IOException {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButtonSafra1 = new javax.swing.JButton();
        jButtonPropriedade1 = new javax.swing.JButton();
        jButtonColheita1 = new javax.swing.JButton();
        jButtonProducao1 = new javax.swing.JButton();
        jButtonAvaliacao1 = new javax.swing.JButton();
        jButtonCepa1 = new javax.swing.JButton();
        jButtonParreiral1 = new javax.swing.JButton();
        jButtonTelefone1 = new javax.swing.JButton();
        jButtonEmail1 = new javax.swing.JButton();
        jButtonVinho1 = new javax.swing.JButton();
        jButtonTerroir1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setTitle("Menu Principal");

        jButtonSafra1.setBackground(new java.awt.Color(242, 242, 242));
        jButtonSafra1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonSafra1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/barrel(3).png"))); // NOI18N
        jButtonSafra1.setText("Safra");
        jButtonSafra1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseSelect(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseDiselect(evt);
            }
        });
        jButtonSafra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSafra1ActionPerformed(evt);
            }
        });

        jButtonPropriedade1.setBackground(new java.awt.Color(242, 242, 242));
        jButtonPropriedade1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonPropriedade1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/house(2).png"))); // NOI18N
        jButtonPropriedade1.setText("Propriedade");
        jButtonPropriedade1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseSelect(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseDiselect(evt);
            }
        });
        jButtonPropriedade1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPropriedade1ActionPerformed(evt);
            }
        });

        jButtonColheita1.setBackground(new java.awt.Color(242, 242, 242));
        jButtonColheita1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonColheita1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/grapes(3).png"))); // NOI18N
        jButtonColheita1.setText("Colheita");
        jButtonColheita1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseSelect(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseDiselect(evt);
            }
        });
        jButtonColheita1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonColheita1ActionPerformed(evt);
            }
        });

        jButtonProducao1.setBackground(new java.awt.Color(242, 242, 242));
        jButtonProducao1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonProducao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/winery.png"))); // NOI18N
        jButtonProducao1.setText("Produção");
        jButtonProducao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseSelect(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseDiselect(evt);
            }
        });
        jButtonProducao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProducao1ActionPerformed(evt);
            }
        });

        jButtonAvaliacao1.setBackground(new java.awt.Color(242, 242, 242));
        jButtonAvaliacao1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonAvaliacao1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/favorite.png"))); // NOI18N
        jButtonAvaliacao1.setText("Avaliação");
        jButtonAvaliacao1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseSelect(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseDiselect(evt);
            }
        });
        jButtonAvaliacao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAvaliacao1ActionPerformed(evt);
            }
        });

        jButtonCepa1.setBackground(new java.awt.Color(242, 242, 242));
        jButtonCepa1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonCepa1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/grapes.png"))); // NOI18N
        jButtonCepa1.setText("Cepa");
        jButtonCepa1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseSelect(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseDiselect(evt);
            }
        });
        jButtonCepa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCepa1ActionPerformed(evt);
            }
        });

        jButtonParreiral1.setBackground(new java.awt.Color(242, 242, 242));
        jButtonParreiral1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonParreiral1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/trees.png"))); // NOI18N
        jButtonParreiral1.setText("Parreiral");
        jButtonParreiral1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseSelect(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseDiselect(evt);
            }
        });
        jButtonParreiral1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonParreiral1ActionPerformed(evt);
            }
        });

        jButtonTelefone1.setBackground(new java.awt.Color(242, 242, 242));
        jButtonTelefone1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonTelefone1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/phone-number.png"))); // NOI18N
        jButtonTelefone1.setText("Telefone");
        jButtonTelefone1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseSelect(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseDiselect(evt);
            }
        });
        jButtonTelefone1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTelefone1ActionPerformed(evt);
            }
        });

        jButtonEmail1.setBackground(new java.awt.Color(242, 242, 242));
        jButtonEmail1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonEmail1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/email.png"))); // NOI18N
        jButtonEmail1.setText("Email");
        jButtonEmail1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseSelect(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseDiselect(evt);
            }
        });
        jButtonEmail1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEmail1ActionPerformed(evt);
            }
        });

        jButtonVinho1.setBackground(new java.awt.Color(242, 242, 242));
        jButtonVinho1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonVinho1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/wine.png"))); // NOI18N
        jButtonVinho1.setText("Vinho");
        jButtonVinho1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseSelect(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseDiselect(evt);
            }
        });
        jButtonVinho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVinho1ActionPerformed(evt);
            }
        });

        jButtonTerroir1.setBackground(new java.awt.Color(242, 242, 242));
        jButtonTerroir1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButtonTerroir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/leaf.png"))); // NOI18N
        jButtonTerroir1.setText("Terroir");
        jButtonTerroir1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseSelect(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseDiselect(evt);
            }
        });
        jButtonTerroir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTerroir1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(242, 242, 242));
        jButton1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/report.png"))); // NOI18N
        jButton1.setText("Relatórios");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mouseSelect(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mouseDiselect(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSafra1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(jButtonProducao1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonTerroir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonVinho1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonCepa1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonPropriedade1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonAvaliacao1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                            .addComponent(jButtonParreiral1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEmail1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTelefone1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonColheita1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonCepa1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonParreiral1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonVinho1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonTerroir1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonPropriedade1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jButtonColheita1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonAvaliacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonProducao1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonSafra1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton2.setBackground(new java.awt.Color(242, 242, 242));
        jButton2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/wine(1).png"))); // NOI18N
        jButton2.setText("Todos os vinhos");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(242, 242, 242));
        jButton3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/barrel(2).png"))); // NOI18N
        jButton3.setText("Safras de um vinho");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(242, 242, 242));
        jButton4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/house(2)_1.png"))); // NOI18N
        jButton4.setText("Produção de Propriedade");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(242, 242, 242));
        jButton5.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/grapes(5).png"))); // NOI18N
        jButton5.setText("Anos mais produtivos por uva");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(242, 242, 242));
        jButton6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/house+grape.png"))); // NOI18N
        jButton6.setText("Uvas de uma propriedade");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(242, 242, 242));
        jButton7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/dionisio/icon/back.png"))); // NOI18N
        jButton7.setText("           Voltar");
        jButton7.setHideActionText(true);
        jButton7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton6MouseExited(evt);
            }
        });
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGap(0, 646, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 546, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSafra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSafra1ActionPerformed
        try {
            SafraView win = new SafraView();
            MenuPrincipal.getDesktopPane().add(win);
            win.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonSafra1ActionPerformed

    private void jButtonPropriedade1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPropriedade1ActionPerformed
        try {
            PropriedadeView win = new PropriedadeView();
            MenuPrincipal.getDesktopPane().add(win);
            win.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonPropriedade1ActionPerformed

    private void jButtonColheita1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonColheita1ActionPerformed
        try {
            ColheitaView win = new ColheitaView();
            MenuPrincipal.getDesktopPane().add(win);
            win.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonColheita1ActionPerformed

    private void jButtonProducao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProducao1ActionPerformed
        try {
            ProduçãoView win = new ProduçãoView();
            MenuPrincipal.getDesktopPane().add(win);
            win.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonProducao1ActionPerformed

    private void jButtonAvaliacao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAvaliacao1ActionPerformed
        try {
            AvaliaçãoView av = new AvaliaçãoView();
            MenuPrincipal.getDesktopPane().add(av);
            av.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonAvaliacao1ActionPerformed

    private void jButtonCepa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCepa1ActionPerformed

        try {
            CepaView cepa = new CepaView();
            MenuPrincipal.getDesktopPane().add(cepa);
            cepa.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonCepa1ActionPerformed

    private void jButtonParreiral1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonParreiral1ActionPerformed
        try {
            ParreiralView win = new ParreiralView();
            MenuPrincipal.getDesktopPane().add(win);
            win.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonParreiral1ActionPerformed

    private void jButtonTelefone1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTelefone1ActionPerformed
        try {
            TelefoneView win = new TelefoneView();
            MenuPrincipal.getDesktopPane().add(win);
            win.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonTelefone1ActionPerformed
    private void jButton2MouseExited(java.awt.event.MouseEvent evt) {
        jButton2.setBackground(ColorUIResource.WHITE);
    }
    private void jButtonEmail1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEmail1ActionPerformed
        try {
            EmailView win = new EmailView();
            MenuPrincipal.getDesktopPane().add(win);
            win.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonEmail1ActionPerformed

    private void jButtonVinho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVinho1ActionPerformed
        try {
            VinhoView win = new VinhoView();
            MenuPrincipal.getDesktopPane().add(win);
            win.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonVinho1ActionPerformed

    private void jButtonTerroir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTerroir1ActionPerformed
        try {
            TerroirView win = new TerroirView();
            MenuPrincipal.getDesktopPane().add(win);
            win.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonTerroir1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        jPanel1.setVisible(false);
        jPanel2.setVisible(true);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        jPanel2.setVisible(false);
        jPanel1.setVisible(true);

    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            VinhosViewSearch1 win = new VinhosViewSearch1();
            MenuPrincipal.getDesktopPane().add(win);
            win.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            SafraVinhoSearch2 win = new SafraVinhoSearch2();
            MenuPrincipal.getDesktopPane().add(win);
            win.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            PropriedadeProduçãoSearch3 win = new PropriedadeProduçãoSearch3();
            MenuPrincipal.getDesktopPane().add(win);
            win.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {
            CepasPropriedadeSearch4 win = new CepasPropriedadeSearch4();
            MenuPrincipal.getDesktopPane().add(win);
            win.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            ProdutividadeUvasSearch5 win = new ProdutividadeUvasSearch5();
            MenuPrincipal.getDesktopPane().add(win);
            win.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Workspace.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void mouseSelect(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseSelect
        JButton btnAux = (JButton) evt.getSource();
        btnAux.setBackground(ColorUIResource.GRAY);
    }//GEN-LAST:event_mouseSelect

    private void mouseDiselect(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mouseDiselect
        JButton btnAux = (JButton) evt.getSource();
        btnAux.setBackground(ColorUIResource.WHITE);

    }//GEN-LAST:event_mouseDiselect

    private void jButton6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseEntered
        JButton btnAux = (JButton) evt.getSource();
        btnAux.setBackground(ColorUIResource.GRAY);
    }//GEN-LAST:event_jButton6MouseEntered

    private void jButton6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseExited

        JButton btnAux = (JButton) evt.getSource();
        btnAux.setBackground(ColorUIResource.WHITE);
    }//GEN-LAST:event_jButton6MouseExited

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButtonAvaliacao1;
    private javax.swing.JButton jButtonCepa1;
    private javax.swing.JButton jButtonColheita1;
    private javax.swing.JButton jButtonEmail1;
    private javax.swing.JButton jButtonParreiral1;
    private javax.swing.JButton jButtonProducao1;
    private javax.swing.JButton jButtonPropriedade1;
    private javax.swing.JButton jButtonSafra1;
    private javax.swing.JButton jButtonTelefone1;
    private javax.swing.JButton jButtonTerroir1;
    private javax.swing.JButton jButtonVinho1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
